
###
 curl --location 'https://api.komodor.com/mgmt/v1/events'  \
 -h 'x-api-key: 21527fbe-3fda-4080-b3ec-931a81a361ba' --header 'Content-Type: application/json' \
 -d '{"eventType": "Example", "summary": "Example of a custom ERROR Event","severity":"information","scope": {},"details": {"Owner": "Hugh Brien","Email": "hughATkomodor.io", slackid:"U04HJNA7Q7J"}}'

POST https://api.komodor.com/mgmt/v1/events
x-api-key: 21527fbe-3fda-4080-b3ec-931a81a361ba
Content-Type: application/json

{
  "eventType": "Frontend  Event",
  "summary": "Host Change Events",
  "severity": "warning",
  "scope": {
    "clusters":["hpbx-mac-cluster"],
    "serviceNames":["frontend"],
    "namespaces":["frontend"]
  },
  "details": {
    "hostname": "server-333332ww",
    "ipaddress": "192.169.1.1",
    "Owner": "Hugh Brien",
    "Email": "hugh@komodor.io"
  }
}


