apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  annotations:
    app.komodor.com/service.link.webhook: http://34.172.104.248:5000/webhook
    app.komodor.com/service.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.webhook: http://34.172.104.248:5000/webhook
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/frontend/commit/eaffc512b27016f6986ff8a309a75edc2d15f1fe
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/frontend
    app.komodor.com/app.ref: eaffc512b27016f6986ff8a309a75edc2d15f1fe

  labels:
    app: frontend
    branch: main
    version: 2.0.4
    author: hughbrien
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        branch: main
        version: 2.0.4
    spec:
      containers:
      - name: frontend
        image: docker.io/hughbrien/frontend:2.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15