apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  annotations:
    app.komodor.com/service.link.frontend: http://34.173.139.195:5000/
    app.komodor.com/service.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.frontend: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/frontend/commit/2701e58f84a353a083564e713c63f9ace4a5a80f
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/frontend
    app.komodor.com/app.ref: 2701e58f84a353a083564e713c63f9ace4a5a80f

  labels:
    app: frontend
    branch: main
    version: latest
    author: hughbrien
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        branch: main
    spec:
      containers:
      - name: frontend
        image: docker.io/hughbrien/frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15