apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  annotations:
    app.komodor.com/service.link.frontend: http://34.173.139.195:5000/
    app.komodor.com/service.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/frontend
     app.komodor.com/deploy.link.frontend-fileset2: https://github.com/hughbrien/frontend/blob/fileset2/frontend.yaml
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/frontend/commit/8f72129cd2be14ef629567213ea39fea64142e3c
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/frontend
    app.komodor.com/app.ref: 8f72129cd2be14ef629567213ea39fea64142e3c

  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/hughbrien/frontend:2.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
