apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    author: hughbrien
    branch: main
    cluster: hpbx-mac-cluster
    version: 3.0.2
  name: frontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        branch: main
        version: 3.0.2
    spec:
      containers:
      - image: docker.io/hughbrien/frontend:3.0.2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 15
        name: frontend
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
