apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/frontend/commit/007b7701713272921e78abb0983a76f71645cf6a
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/frontend
    app.komodor.com/app.ref: 007b7701713272921e78abb0983a76f71645cf6a

  labels:
    tags.datadoghq.com/env: "development"
    tags.datadoghq.com/service: "frontend"
    tags.datadoghq.com/version: "2.1.10"
    cluster: hpbx-mac-cluster
    branch: main
    author: hughbrien
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        branch: main
        version: 2.1.10
    spec:
      containers:
      - name: frontend
        image: docker.io/hughbrien/frontend:2.1.10
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 200m
            # Reduce by 5 from 250 recommended
            memory: 256Mi
            # recude by 22 from 256 recommended

