apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  annotations:
    sidecar.speedscale.com/inject: "true"

#    link.argocd.argoproj.io/external-link: https://app.komodor.com/main/services/{{account-name}}.{{cluster}}-{{namespace}}.{{service}}
    link.argocd.argoproj.io/external-link: https://app.komodor.com/services/demo.hpbx-mac-cluster-frontend.frontend?accountId=fe52cf0b-42da-4ae1-a8db-776e0f1335a0&
    app.komodor.com/service.link.jenkins: http://localhost:8001/version
    app.komodor.com/deploy.link.jenkins: http://localhost:8001/version
    app.komodor.com/service.link.argocd: https://localhost:8090/applications/argocd/newfrontend?operation=false&resource=
    app.komodor.com/deploy.link.argocd: https://localhost:8090/applications/argocd/newfrontend?operation=false&resource=

    app.komodor.com/service.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.webhook: http://localhost:8001
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/frontend/commit/08ca7ddbba2902f2d6af0500fdc4aaf638bfa9bf
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/frontend
    app.komodor.com/app.ref: 08ca7ddbba2902f2d6af0500fdc4aaf638bfa9bf

  labels:
    cluster: hpbx-mac-cluster
    app: frontend
    branch: main
    version: 2.1.6
    author: hughbrien
    notes: 2.1.6
    owner: hughbrien

spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        branch: main
        version: 2.1.6
    spec:
      containers:
      - name: frontend
        image: docker.io/hughbrien/frontend:2.1.6
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 2Gi
            memory: 512Gi
          requests:
            cpu: 245m
            # Reduce by 5 from 250 recommended
            ephemeral-storage: 1Gi
            memory: 234Mi
            # recude by 22 from 256 recommended
