apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  annotations:
    link.argocd.argoproj.io/external-link: https://app.komodor.com/main/deep-dive/{{account-name}}.{{cluster}}-{{namespace}}.{{service}}
    app.komodor.com/service.link.webhook: http://localhost:8001/version
    app.komodor.com/service.link.jenkins: http://localhost:8001/version
    app.komodor.com/deploy.link.jenkins: http://localhost:8001/version
    app.komodor.com/service.link.argocd: https://localhost:8090/applications/argocd/newfrontend?operation=false&resource=
    app.komodor.com/deploy.link.argocd: https://localhost:8090/applications/argocd/newfrontend?operation=false&resource=

    app.komodor.com/service.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/frontend
    app.komodor.com/deploy.link.webhook: http://localhost:8001
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/frontend/commit/1c2bd4361c1e40b434f61a9cab168b03e9a29df1
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/frontend
    app.komodor.com/app.ref: 1c2bd4361c1e40b434f61a9cab168b03e9a29df1

  labels:
    cluster: hpbx-mac-cluster
    app: frontend
    branch: main
    version: 2.1.4
    author: hughbrien
    notes: 2.1.4
    owner: hughbrien

spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
        branch: main
        version: 2.1.4
    spec:
      containers:
      - name: frontend
        image: docker.io/hughbrien/frontend:2.1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 2Gi
            memory: 512Gi
          requests:
            cpu: 245m
            # Reduce by 5 from 250 recommended
            ephemeral-storage: 1Gi
            memory: 234Mi
            # recude by 22 from 256 recommended
